//go:build linux && amd64

package main

import "syscall"

// resolveSyscallName maps a syscall name string to its numeric value for amd64.
// Returns -1 if the name is unknown.
func resolveSyscallName(name string) int {
	switch name {
	case "read":
		return syscall.SYS_READ
	case "write":
		return syscall.SYS_WRITE
	case "open":
		return syscall.SYS_OPEN
	case "close":
		return syscall.SYS_CLOSE
	case "stat":
		return syscall.SYS_STAT
	case "fstat":
		return syscall.SYS_FSTAT
	case "lstat":
		return syscall.SYS_LSTAT
	case "poll":
		return syscall.SYS_POLL
	case "lseek":
		return syscall.SYS_LSEEK
	case "mmap":
		return syscall.SYS_MMAP
	case "mprotect":
		return syscall.SYS_MPROTECT
	case "munmap":
		return syscall.SYS_MUNMAP
	case "brk":
		return syscall.SYS_BRK
	case "rt_sigaction":
		return syscall.SYS_RT_SIGACTION
	case "rt_sigprocmask":
		return syscall.SYS_RT_SIGPROCMASK
	case "rt_sigreturn":
		return syscall.SYS_RT_SIGRETURN
	case "ioctl":
		return syscall.SYS_IOCTL
	case "pread64":
		return syscall.SYS_PREAD64
	case "pwrite64":
		return syscall.SYS_PWRITE64
	case "readv":
		return syscall.SYS_READV
	case "writev":
		return syscall.SYS_WRITEV
	case "access":
		return syscall.SYS_ACCESS
	case "pipe":
		return syscall.SYS_PIPE
	case "select":
		return syscall.SYS_SELECT
	case "sched_yield":
		return syscall.SYS_SCHED_YIELD
	case "mremap":
		return syscall.SYS_MREMAP
	case "msync":
		return syscall.SYS_MSYNC
	case "mincore":
		return syscall.SYS_MINCORE
	case "madvise":
		return syscall.SYS_MADVISE
	case "dup":
		return syscall.SYS_DUP
	case "dup2":
		return syscall.SYS_DUP2
	case "pause":
		return syscall.SYS_PAUSE
	case "nanosleep":
		return syscall.SYS_NANOSLEEP
	case "getitimer":
		return syscall.SYS_GETITIMER
	case "alarm":
		return syscall.SYS_ALARM
	case "setitimer":
		return syscall.SYS_SETITIMER
	case "getpid":
		return syscall.SYS_GETPID
	case "sendfile":
		return syscall.SYS_SENDFILE
	case "socket":
		return syscall.SYS_SOCKET
	case "connect":
		return syscall.SYS_CONNECT
	case "accept":
		return syscall.SYS_ACCEPT
	case "sendto":
		return syscall.SYS_SENDTO
	case "recvfrom":
		return syscall.SYS_RECVFROM
	case "sendmsg":
		return syscall.SYS_SENDMSG
	case "recvmsg":
		return syscall.SYS_RECVMSG
	case "shutdown":
		return syscall.SYS_SHUTDOWN
	case "bind":
		return syscall.SYS_BIND
	case "listen":
		return syscall.SYS_LISTEN
	case "getsockname":
		return syscall.SYS_GETSOCKNAME
	case "getpeername":
		return syscall.SYS_GETPEERNAME
	case "socketpair":
		return syscall.SYS_SOCKETPAIR
	case "setsockopt":
		return syscall.SYS_SETSOCKOPT
	case "getsockopt":
		return syscall.SYS_GETSOCKOPT
	case "clone":
		return syscall.SYS_CLONE
	case "fork":
		return int(sysFORK)
	case "vfork":
		return int(sysVFORK)
	case "execve":
		return syscall.SYS_EXECVE
	case "exit":
		return syscall.SYS_EXIT
	case "wait4":
		return syscall.SYS_WAIT4
	case "kill":
		return syscall.SYS_KILL
	case "uname":
		return syscall.SYS_UNAME
	case "fcntl":
		return syscall.SYS_FCNTL
	case "flock":
		return syscall.SYS_FLOCK
	case "fsync":
		return syscall.SYS_FSYNC
	case "fdatasync":
		return syscall.SYS_FDATASYNC
	case "ftruncate":
		return syscall.SYS_FTRUNCATE
	case "getdents":
		return syscall.SYS_GETDENTS
	case "getcwd":
		return syscall.SYS_GETCWD
	case "chdir":
		return syscall.SYS_CHDIR
	case "rename":
		return syscall.SYS_RENAME
	case "mkdir":
		return syscall.SYS_MKDIR
	case "rmdir":
		return syscall.SYS_RMDIR
	case "creat":
		return syscall.SYS_CREAT
	case "link":
		return syscall.SYS_LINK
	case "unlink":
		return syscall.SYS_UNLINK
	case "symlink":
		return syscall.SYS_SYMLINK
	case "readlink":
		return syscall.SYS_READLINK
	case "chmod":
		return syscall.SYS_CHMOD
	case "fchmod":
		return syscall.SYS_FCHMOD
	case "chown":
		return syscall.SYS_CHOWN
	case "fchown":
		return syscall.SYS_FCHOWN
	case "lchown":
		return syscall.SYS_LCHOWN
	case "umask":
		return syscall.SYS_UMASK
	case "gettimeofday":
		return syscall.SYS_GETTIMEOFDAY
	case "getrlimit":
		return syscall.SYS_GETRLIMIT
	case "getrusage":
		return syscall.SYS_GETRUSAGE
	case "sysinfo":
		return syscall.SYS_SYSINFO
	case "times":
		return syscall.SYS_TIMES
	case "ptrace":
		return syscall.SYS_PTRACE
	case "getuid":
		return syscall.SYS_GETUID
	case "syslog":
		return syscall.SYS_SYSLOG
	case "getgid":
		return syscall.SYS_GETGID
	case "setuid":
		return syscall.SYS_SETUID
	case "setgid":
		return syscall.SYS_SETGID
	case "geteuid":
		return syscall.SYS_GETEUID
	case "getegid":
		return syscall.SYS_GETEGID
	case "setpgid":
		return syscall.SYS_SETPGID
	case "getppid":
		return syscall.SYS_GETPPID
	case "getpgrp":
		return syscall.SYS_GETPGRP
	case "setsid":
		return syscall.SYS_SETSID
	case "setreuid":
		return syscall.SYS_SETREUID
	case "setregid":
		return syscall.SYS_SETREGID
	case "getgroups":
		return syscall.SYS_GETGROUPS
	case "setgroups":
		return syscall.SYS_SETGROUPS
	case "setresuid":
		return syscall.SYS_SETRESUID
	case "getresuid":
		return syscall.SYS_GETRESUID
	case "setresgid":
		return syscall.SYS_SETRESGID
	case "getresgid":
		return syscall.SYS_GETRESGID
	case "getpgid":
		return syscall.SYS_GETPGID
	case "setfsuid":
		return syscall.SYS_SETFSUID
	case "setfsgid":
		return syscall.SYS_SETFSGID
	case "getsid":
		return syscall.SYS_GETSID
	case "capget":
		return syscall.SYS_CAPGET
	case "capset":
		return syscall.SYS_CAPSET
	case "sigaltstack":
		return syscall.SYS_SIGALTSTACK
	case "utimensat":
		return syscall.SYS_UTIMENSAT
	case "futex":
		return syscall.SYS_FUTEX
	case "epoll_create":
		return syscall.SYS_EPOLL_CREATE
	case "epoll_ctl":
		return syscall.SYS_EPOLL_CTL
	case "epoll_wait":
		return syscall.SYS_EPOLL_WAIT
	case "eventfd2":
		return syscall.SYS_EVENTFD2
	case "fallocate":
		return syscall.SYS_FALLOCATE
	case "getrandom":
		return int(sysGETRANDOM)
	case "membarrier":
		return int(sysMEMBARRIER)
	case "mlock":
		return syscall.SYS_MLOCK
	case "munlock":
		return syscall.SYS_MUNLOCK
	case "mlockall":
		return syscall.SYS_MLOCKALL
	case "munlockall":
		return syscall.SYS_MUNLOCKALL
	case "prctl":
		return syscall.SYS_PRCTL
	case "arch_prctl":
		return syscall.SYS_ARCH_PRCTL
	case "set_tid_address":
		return syscall.SYS_SET_TID_ADDRESS
	case "set_robust_list":
		return syscall.SYS_SET_ROBUST_LIST
	case "clock_gettime":
		return syscall.SYS_CLOCK_GETTIME
	case "clock_getres":
		return syscall.SYS_CLOCK_GETRES
	case "tgkill":
		return syscall.SYS_TGKILL
	case "exit_group":
		return syscall.SYS_EXIT_GROUP
	case "openat":
		return syscall.SYS_OPENAT
	case "mkdirat":
		return syscall.SYS_MKDIRAT
	case "mknodat":
		return syscall.SYS_MKNODAT
	case "fchownat":
		return syscall.SYS_FCHOWNAT
	case "futimesat":
		return syscall.SYS_FUTIMESAT
	case "newfstatat":
		return syscall.SYS_NEWFSTATAT
	case "unlinkat":
		return syscall.SYS_UNLINKAT
	case "renameat":
		return syscall.SYS_RENAMEAT
	case "linkat":
		return syscall.SYS_LINKAT
	case "symlinkat":
		return syscall.SYS_SYMLINKAT
	case "readlinkat":
		return syscall.SYS_READLINKAT
	case "fchmodat":
		return syscall.SYS_FCHMODAT
	case "faccessat":
		return syscall.SYS_FACCESSAT
	case "pselect6":
		return syscall.SYS_PSELECT6
	case "ppoll":
		return syscall.SYS_PPOLL
	case "signalfd":
		return syscall.SYS_SIGNALFD
	case "signalfd4":
		return syscall.SYS_SIGNALFD4
	case "timerfd_create":
		return syscall.SYS_TIMERFD_CREATE
	case "timerfd_settime":
		return syscall.SYS_TIMERFD_SETTIME
	case "timerfd_gettime":
		return syscall.SYS_TIMERFD_GETTIME
	case "inotify_init":
		return syscall.SYS_INOTIFY_INIT
	case "inotify_init1":
		return int(sysINOTIFY_INIT1)
	case "inotify_add_watch":
		return syscall.SYS_INOTIFY_ADD_WATCH
	case "inotify_rm_watch":
		return syscall.SYS_INOTIFY_RM_WATCH
	case "personality":
		return syscall.SYS_PERSONALITY
	case "openat2":
		return int(sysOPENAT2)
	default:
		return -1
	}
}
